### ISSUE TITLE
CSS Variables not polyfilled for IE11 in "dist" build

### ISSUE THREAD

**Issue by auderer** [ionic-team/stencil#1200]
**Stencil version:**

```
 @stencil/core@0.15.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

CSS variables are polyfilled in "www" build, but not in "dist" components used in an external React app. The CSS variable line is not replaced causing the style to break on IE11.

**Expected behavior:**

CSS variables should be polyfilled for IE11 in "dist" components.

**Steps to reproduce:**

1. Start with the stencil component starter
2. Use a CSS variable: `background-color: var(--app-primary-color, #448aff)`
3. `npm run build`
4. Use the component in an external React app
5. Open the react app in IE11. The background color will not be set at all.

**Other information:**

I believe the polyfill should set it to the fallback color, which seems to be what happens in the `www` build. It's only when used in an external app that this breaks.

**Comment by loudmouth** [comment]
Is it possible that the relevant polyfill isn't compiled into the final output? I have been searching dist for references to [ShadyCSS](https://github.com/webcomponents/shadycss) as it was my understanding this was the relevant polyfill that Stencil says it's using in the README, but I don't see any use of this polyfill.

**Comment by petermikitsh** [comment]
I can verify this problem occurs in IE11 for me as well. Will this be addressed in 1.x?

**Comment by stanley85** [comment]
Still missing the vars for IE11 @1.0.2 @manucorporat do you have an idea what is missing?

**Comment by adamdbradley** [comment]
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks
