### ISSUE TITLE
Props reflect: true not updating DOM attribute

### ISSUE THREAD

**Issue by liester** [ionic-team/stencil#2066]
**Stencil version:**
```
 @stencil/core@1.8.1
```

**I'm submitting a:**
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
I'm assigning a property value of my stencil component via:
 const myComponent = document.querySelector('my-component');
myComponent.first = 'levi'

My stencil component has: @Prop({reflect:true}) first: string;

The value appears to be assigned correctly in the component and is displayed correctly on the UI.  However, the attribute in the DOM is not reflecting the change as I would expect it to.
![image](https://user-images.githubusercontent.com/6137420/70368415-95177380-186f-11ea-8a9e-62f50c41e1d5.png)

**Expected behavior:**
I would expect the attribute 'first' on the DOM to be updated to 'levi'.

**Steps to reproduce:**
Thinking it was something odd I was doing or a dependency I might have added I went back to the stenciljs docs and used the 'Getting Started' steps: https://stenciljs.com/docs/getting-started

1. npm init stencil
2. select the "component" starter.
3. npm install @stencil/core@latest --save-exact
4. In the generated my-component.tsx file, update:
``` @Prop() first: string;```
to be
``` @Prop({reflect:true}) first: string;```
5. In index.html, directly under body end tag add:
```javascript
<script>
  setTimeout(()=>{
    const myComponent = document.querySelector('my-component');
    myComponent.first = 'levi'
  }, 3000)
</script>
```

**Related code:**

```tsx
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop({reflect:true}) first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    return <div>Hello, World! I'm {this.getText()}</div>;
  }
}
```

```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <title>Stencil Component Starter</title>

  <script type="module" src="/build/test-props.esm.js"></script>
  <script nomodule src="/build/test-props.js"></script>

</head>
<body>

  <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>

</body>
<script>
  setTimeout(()=>{
    const myComponent = document.querySelector('my-component');
    myComponent.first = 'levi'
  }, 3000)
</script>
</html>
```

**Other information:**
I haven't had much luck googling for this particular issue.  The documentation I see on stenciljs' site makes it seem like this is pretty simple and should work.  It makes me think I'm not doing something right but I'm not sure what it is. 
Just for fun I also tried 'reflectToAttr: true' but that didn't seem to help either.
Thank you in advance for any help someone can provide :)

**Comment by dgibson666** [comment]
I'm still using reflectToAttr because reflect seemed to do nothing for me (and I wasn't sure if it had another purpose)

**Comment by bsastregx** [comment]
Same issue here. @stencil/core v1.8.2

**Comment by bsastregx** [comment]
Is there a way I can give some kind of vote to this issue?

**Comment by dedd1993** [comment]
Same issue here. @stencil/core v1.8.3
Using "reflect" not "reflectToAttr" since that is how is defined on the documentation.

**Comment by stanley85** [comment]
I am not sure but maybe its related to whats written in the Docs about reactive data. So mutating the Object is not triggering the re-render. Instead it needs to change completely, like so
`myComponent = {...myComponent, first: 'levi'}`

**Comment by reedycat** [comment]
Same issue here. @stencil/core v1.8.4
Using "reflect".

**Comment by starikcetin** [comment]
Same issue. Very annoying.

**Comment by brian-cruickshank** [comment]
Same issue (versions 1.8.0 - 1.8.5).  Works properly in @stencil/core v1.8.7

**Comment by reedycat** [comment]
This is strange, I did not change anything, but it began to work.

**Comment by starikcetin** [comment]
> This is strange, I did not change anything, but it began to work.

Maybe you installed an update due to NPM version ranges.

**Comment by hnipps** [comment]
I'm still experiencing the issue with 1.8.11.

**Comment by hnipps** [comment]
In case anyone is struggling with this here's my workaround:
```tsx
@Component({
  tag: "my-component",
  styleUrl: "my-component.css",
  shadow: true
})
export class MyComponent {
  @Prop() myAttr: string;
  @Element() host: HTMLElement;

  updateAttribute(someValue) {
    this.host.setAttribute("my-attr", someValue);
  }

  render() {
    // Whatever JSX...
  }
}
```

**Comment by kensodemann** [comment]
I have a repo showing this as well: https://github.com/kensodemann/test-property

That repo is using `@stencil/core@1.8.8` and it works fine. But if you upgrade `@stencil/core` to `1.8.9` then the `foo` property stops being reflected.

**Comment by manucorporat** [comment]
This should be fixed!

**Comment by AndrewZagovora** [comment]
@manucorporat 
Hello!
The issue still can be replicate on @stencil/core@1.13.0 version.
The "reflect" option does not make any changes from inside of the component, The value of the property itself changes, but it does not affect the attribute. In my case, I cannot remove "open" attribute hide the component using ":host([open])" selector. The "open" attribute still appears with even though the property value is set to false from inside of the component.
If I try to remove the "open" attribute from outside, it works fine.

**Comment by ticklemycode** [comment]
I'm on Stencil 2.5.2 and I'm seeing the reflect is slow to update the attribute.
![image](https://user-images.githubusercontent.com/32107888/145516180-e60b5cb9-f007-41a8-a761-3f642e6d6ef7.png)

**Comment by biijoy508** [comment]
> 

In case of boolean , you need to set attribute and remove attribute

**Comment by henryongsparkjoy** [comment]
Using @stencil/core@2.15.0 and it also happened when deployed as web components in gcloud but somehow works locally

**Comment by milanbargiel** [comment]
In version @stencil/core@3.3.0, I still have the same issue. Even though reflect is set to `true` for a Prop, the value is not updated in the DOM. I used @hnipps workaround.
