### ISSUE TITLE
1.12.3 "Composite projects may not disable declaration emit."

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#2349]
**Stencil version:**

```
 @stencil/core@1.12.3
```

**I'm submitting a:**

[x bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
In dev mode the latest version `1.12.3` throws this error again in a `lerna` context although was fixed some time ago. It's back :-) All `tsconfig`files a re set to `declaration: true`.

**Expected behavior:**
Respects tsconfig with `declaration: true` and doesn't throw error.

**Steps to reproduce:**
Clone and run that repo: https://github.com/bitflower/stencil-lerna

![image](https://user-images.githubusercontent.com/6666636/78803993-ee2f1980-79bf-11ea-8965-0a7b8f048578.png)
![image](https://user-images.githubusercontent.com/6666636/78804025-f5eebe00-79bf-11ea-84f0-69f3b4fb3eb0.png)

**Comment by bitflower** [comment]
Still happening with `1.12.6`

**Comment by bitflower** [comment]
Further analysis shows that there is a difference between prod and dev build on this line:
![image](https://user-images.githubusercontent.com/6666636/80565039-c8f65f80-89ef-11ea-971a-1bfacc53d042.png)

On prod build this returns:
```
[]
```

whereas in dev mode it returns:

```
[ { file: undefined,
    start: undefined,
    length: undefined,
    messageText: 'Composite projects may not disable declaration emit.',
    category: 1,
    code: 6304,
    reportsUnnecessary: undefined } ]
```

**Comment by bitflower** [comment]
The loaded config is exactly the same so it must be changed somehow during transpile:
![stencil-ts-config](https://user-images.githubusercontent.com/6666636/80640146-4c04cd80-8a63-11ea-94bd-374bee645201.gif)

**Comment by bitflower** [comment]
I got it working with the help of @simonhaenisch by changing this line:
![image](https://user-images.githubusercontent.com/6666636/80646991-0699cd80-8a6e-11ea-8499-6856a5a0fd84.png)

Result:
![image](https://user-images.githubusercontent.com/6666636/80647035-15808000-8a6e-11ea-88f0-141227eb679f.png)

**Comment by bitflower** [comment]
Conversation from Slack for reference:

simonhaenisch(wird in einem neuem Tab geöffnet)  vor 6 Tagen
@Matthias Max not sure but wouldn't it just fix it if you explicitly set buildDist: true in your stencil config?




simonhaenisch(wird in einem neuem Tab geöffnet)  vor 6 Tagen
it's an actual option for stencil.config.ts
image.png 
image.png
(wird in einem neuem Tab geöffnet)



Matthias Max(wird in einem neuem Tab geöffnet)  vor 5 Tagen
Agreed this is maybe one way. But I would have expected the typescript setup to be the same for dev and prod without having to adjust the config. Especially if the error doesn‘t lead you at all to the right place. Do you agree?

So would this be more of a warning that should be printed instead of the „fix“ I PR‘ed? @adam  what do you think?

Matthias Max(wird in einem neuem Tab geöffnet)  vor 5 Tagen
Like, this took me ages to find and I want others to not have to fall into this trap.

adam(wird in einem neuem Tab geöffnet)  vor 5 Tagen
sorry pretty disconnected right now, can you ping me again on Monday? We’ll be able to dedicate a lot more time next week

Matthias Max(wird in einem neuem Tab geöffnet)  vor 5 Tagen
Awesome, cu :victory:

**Comment by bitflower** [comment]
https://stencil-worldwide.slack.com/archives/C79EANFL7/p1588190263240400

**Comment by simonhaenisch** [comment]
TBH I don't really get the `buildDist` option of the config... maybe it should be removed, and its logic be replaced with `outputTargets.some(target => target.type === 'dist')`? Is it a legacy option from before output targets were a thing? If so, I'd definitely get rid of it, or at least deprecate it and  change the implementation so that it doesn't create different behavior anymore.

**Comment by manucorporat** [comment]
Fixed!

**Comment by ipepiji** [comment]
I still get "Error: error TS6304: Composite projects may not disable declaration emit."

**Comment by simonhaenisch** [comment]
Then you should probably open a new issue instead of commenting on this one that was fixed 3 years ago which means this time it's probably only tangentially related to the cause of the issue back then? You can mention this issue in your new one for reference, and your new issue will actually get looked at by the current maintainers.

I've unsubscribed from this issue now but please be aware that when you comment on an old issue, you notify everyone who's been active on it before.

**Comment by Yokohmariam** [comment]
inside tsconfig.base.json  add
```
"compilerOptions:{
    "declaration": true,
    "composite": true,
    "emitDeclarationOnly": true,
}
```
inside tsconfig.storybook.json add
```
"compilerOptions":{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "composite": true,
    "declaration": true,
    "declarationMap": true,

  },
  }
```

**Comment by oshliaer** [comment]
@Yokohmariam, thank you!
