### ISSUE TITLE
Components not loading in Safari 10.1 

### ISSUE THREAD

**Issue by maxjustus** [ionic-team/stencil#2392]
**Stencil version:**

```
 @stencil/core@1.12.4
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When attempting to load a page with stencil components in Safari 10.1 on both Mac OS and iOS no custom elements on the page get upgraded/hydrated, and no js errors appear in the console.

![Screen Shot 2020-04-24 at 3 26 43 PM](https://user-images.githubusercontent.com/24899/80261736-1c5b5d00-8640-11ea-8547-4957717c7725.png)

Prior to upgrading to 1.12.14 we were running 1.5.3 and using server side code to only serve the ES modules JS file to Safari 10.1 as a workaround for 10.1's issue with loading and evaluating both the `type="module"` and `nomodule` files and we were able to get it working. Since the change that makes Safari 10.1 use the es5 bundle we removed that business logic but even with that change nothing is working.

**Expected behavior:**

Components should load in Safari 10.1

**Steps to reproduce:**

You can actually observe this issue on the ionic framework docs site by loading up one of the example pages in Safari 10.1 https://ionicframework.com/docs/demos/api/input/index.html
You will see a blank page, and if you open the console, you'll see no errors. Inspecting the DOM will reveal that none of the components on the page have a "hydrated" class and they're all empty.

**Comment by manucorporat** [comment]
This should be fixed in latest stencil, there is a settting in stencil.config.ts called `extras` enable the `safari10` option by setting it to true.

**Comment by warapitiya** [comment]
I can confirm that this is **still not working**.

Browser:
![image](https://user-images.githubusercontent.com/6380518/88658307-cba74480-d105-11ea-8feb-3ece7789de92.png)

Tested on Stencil: v1.2.0 and v1.7.1 both.

Issue Repo: https://github.com/warapitiya/stencil-safari10

**Comment by FortinFred** [comment]
Same here, it's not working on iOS 10.3.

This issue should be reopened!

**Comment by linuxonrails** [comment]
Same here! Last Stencil version with Safari 10.3.

It's important. Please, reopen!

**Comment by linuxonrails** [comment]
> You can actually observe this issue on the ionic framework docs site by loading up one of the example pages in Safari 10.1 https://ionicframework.com/docs/demos/api/input/index.html You will see a blank page, and if you open the console, you'll see no errors. Inspecting the DOM will reveal that none of the components on the page have a "hydrated" class and they're all empty.

With Safari 11 in https://ionicframework.com/docs/demos/api/input/index.html I have javascripts errors:

  `SyntaxError: Unexpected identifier 'i'. Expected a ';' following a return statement. undefinedpromiseReactionJob @ (program):1`

With Safari 10, nothing happens (no render, no errors) :disappointed:

**Comment by linuxonrails** [comment]
@manucorporat Can you confirm that it's fixed?
