### ISSUE TITLE
"Browserslist: caniuse-lite is outdated" spams output when buildEs5 is truthy

### ISSUE THREAD

**Issue by illepic** [ionic-team/stencil#2784]
**Stencil version:**

```
 @stencil/core@2.3.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
Compiling with `buildEs5: prod` (or anything truthy) results in the repeated message to update caniuse-lite:

![image](https://user-images.githubusercontent.com/295127/103391521-c4c69880-4ace-11eb-9fe5-a340424ba8e4.png)

**Expected behavior:**

Running the suggested `npx browserslist@latest --update-db` does not modify `package-lock.json` nor make the message go away. Another suggestion to update nested dependencies via `npm --depth 20 update caniuse-lite browserslist` also did not make the message go away.

**Steps to reproduce:**

In `stencil.config.ts`, set `buildEs5: true`, then run `stencil build` to see spammed output.

**Comment by claviska** [comment]
`npm ls browserslist` shows it's being used by autoprefixer and core-js-builder. Updating those should solve it.

Looks like autoprefixer bumped to [version 10](https://github.com/postcss/autoprefixer/blob/main/CHANGELOG.md#100-alis-volat-propriis) (Stencil is currently using 9) so we'll need to make sure that doesn't break.

**Comment by claviska** [comment]
Autoprefixer 10 seems to be fine and gives us the latest `browserslist`.

For some reason, we're pinning `core-js-builder` to 3.6. We need 3.8 to get the most recent `browerslist` version, but 3.8 seems to break things.

**Comment by claviska** [comment]
I made an attempt to fix this in #2787 but despite everything being up to date, I'm still seeing the warnings. Not sure why, so we'll have to circle back to this.

**Comment by dutscher** [comment]
i found that `"autoprefixer": "10.2.5"` is fixed since several releases and in the npm package is a binary https://github.com/ionic-team/stencil/blob/main/src/sys/node/bundles/autoprefixer.js which didnt consume newer browserslist.
i cant figure out how to configure my stencil config that these 7 annoying messages will removed.

cheers

**Comment by vaibhavshn** [comment]
Facing a similar issue, but running update does update my `package-lock.json`.

Still seeing these logs.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/6205961/187684505-453fdf79-20f2-46fe-be1c-1f1b8a80a8f5.png">

**Comment by rwaskiewicz** [comment]
👋 I'm going to label this issue to get it ingested into the team's backlog

**Comment by rwaskiewicz** [comment]
This will be fixed in an upcoming version of Stencil, v2.19.0.

**Comment by rwaskiewicz** [comment]
This has been fixed in [Stencil v2.19.0](https://github.com/ionic-team/stencil/releases/tag/v2.19.0), which was just released. I'm going to close this issue as a result. If this bug should reappear, feel free to open a new issue. Thanks!
