### ISSUE TITLE
Generated files are exported in project root

### ISSUE THREAD

**Issue by dimi-nk** [ionic-team/stencil#313]
**Stencil version:**

```
 @stencil/core@0.0.8-2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When running `npm run dev`, the stencil compiler is spitting files on the project root.

**Expected behavior:**

No files should appear.

**Steps to reproduce:**

0. clone `stencil-component-starter` & run `npm install`
1. run `npm run dev`
2. `my-component.sc.js` appears on the root of the project

**Related code:**
N/A

**Other information:**

N/A

**Comment by jgw96** [comment]
Hey! This is fixed in the latest release. `npm install @stencil/core@0.0.8-5 --save` will get you the latest release. Thanks!

**Comment by dimi-nk** [comment]
@jgw96 Still getting the same behaviour with 0.0.8-5
![image](https://user-images.githubusercontent.com/2273840/32958141-7f791d20-cbb5-11e7-8d95-56905a29d5cf.png)
