### ISSUE TITLE
Custom Decorators break simplest test

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#364]
**Stencil version:**

```
 @stencil/core@0.0.9-0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Simply newing up class that uses a non-Stencil decorator fails in the test

**Expected behavior:**

Test works

**Steps to reproduce:**

https://github.com/mattdsteele/stencil-test-decorators

**Other information:**

Possibly related to #355

**Comment by jthoms1** [comment]
This is fixed with commit 68dcc847dc6d4d1bbb4349f09c10e39f67f2be63.

**Comment by cary-smith** [comment]
Unfortunately 0.0.9-2 did not fix this. The issue still exists.

**Comment by jthoms1** [comment]
I will create a test for this in our code base and ensure that we do not have future regressions.

**Comment by jthoms1** [comment]
Tests were added with 71f3c16949e1eadb575a9134938f2f11b517c08c.
