### ISSUE TITLE
Production build fails to create components with shadow root attached

### ISSUE THREAD

**Issue by dimi-nk** [ionic-team/stencil#419]
**Stencil version:**

```
 @stencil/core@0.1.5<version>
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

While `npm start` seems to generate the shadow root correctly, `npm run build` fails to properly attach the shadow root.

**Expected behavior:**

Shadow root is attached on both cases

**Steps to reproduce:**

- clone repo mentioned below
- execute `npm run build`
- execute `npm run serve`
- check the generated HTML
- `<my-icon>` looks like this:
![image](https://user-images.githubusercontent.com/2273840/35000865-6128e40c-fadd-11e7-8d00-ee0781616405.png)

Expected result (via `npm start` build) is this:
![image](https://user-images.githubusercontent.com/2273840/35000913-8267d11e-fadd-11e7-959b-0ca37083840c.png)

**Related code:**
Example repo: https://github.com/dimi-nk/stencil-component-starter

**Other information:**

**Comment by jgw96** [comment]
Looking into this

**Comment by dimi-nk** [comment]
Thought of opening an issue, since it might get lost in slack

**Comment by shprink** [comment]
Might be the problem I encountered on https://github.com/shprink/WC-Polymer-Stencil-todo. the build finishes but files are empty.

Reproduce:

```
git clone git@github.com:shprink/WC-Polymer-Stencil-todo.git test
cd test/stencil
yarn
npm start // works!
npm run build // does not
```

**Comment by jgw96** [comment]
Alright, so weird thing. Shadow Dom in prod buidls is working fine in the `stencil-app-starter` but not in the component starter. Marking this as a legit bug. Thanks for opening this bug @dimi-nk !

**Comment by dimi-nk** [comment]
Could the `--prerender` flag on `"build": "stencil build --prerender"` make a difference?

**Comment by dimi-nk** [comment]
The problem was created between `0.1.0-0` and `0.1.0`. `0.1.0-0` seems to be the last release where I get a shadow dom after running `npm run build`.

**Comment by adamdbradley** [comment]
I just tested this in `0.2.2` and should be fixed now. Thanks for the report!

**Comment by dimi-nk** [comment]
@adamdbradley I've tested with `0.2.2` and I still see the problem. What I did:

In the stencil components repo:
- Updated to `0.2.2`
- `rm -rf node_modules dist`
- `npm install`
- `npm run build`
- `yarn link`

In the app repo:
- `rm -rf node_modules`
- `yarn`
- `yarn link component-repo`
- `ng serve`
- Still get components without a shadow root

**Comment by adamdbradley** [comment]
Curious, do you have some components that use shadow and some that don't?

**Comment by dimi-nk** [comment]
I have a few 'demo' components inside the project (using the actual components as a showcase), but those are not part of the bundled components.

**Comment by marlonicus** [comment]
I am having the same problem with a similar setup to dimi-nk (running Node 7.10 on MacOS Sierra).

I have built a few simple components using the stencil-component-starter project as a base. These work just fine when built through dev mode (`stencil build --dev`), but when I do a prod build (`stencil build`), the components don't have shadow dom. 

I am using @stencil/core 0.2.3, but I have tried with 0.2.2 and 0.2.1. My stencil config looks like:

```
exports.config = {
  namespace: 'xxx',
  generateDistribution: true,
  bundles: [
    { components: ['xxx'] }
  ],
  globalScript: 'src/envvars.ts',
  copy: [
    { src: 'assets' }
  ],
  globalStyle: 'src/global/variables.css',
  publicPath: process.env.STENCIL_BASE_URL,
};

exports.devServer = {
  root: 'www',
  watchGlob: '**/**'
}

```

And my components aren't doing anything fancy or special, this is my Component decorator:

```
@Component({
  tag: 'xxx-button',
  styleUrl: 'xxx-button.scss',
  // shadow: true, // Tried with and without
})
```

I have tried with and without shadow set on all components (as per @adamdbradley's comment), but to no avail. I have also tried building with the `--prerender` flag (just in case it was a strange quirk with that).

Let me know if you need any more info!

**Comment by dimi-nk** [comment]
Here's my config as well, in case it helps:
```javascript
exports.config = {
    namespace           : 'xxx',
    generateDistribution: true,
    bundles             : [
        {components: ['xxx-dropdown-menu', 'xxx-draggable-grid', 'xxx-draggable-grid-item', 'xx-icon', 'iz-select']}
    ],
    collections         : [{name: '@stencil/router'}]
};

exports.devServer = {
    root     : 'www',
    watchGlob: '**/**'
};
```

**Comment by mattdsteele** [comment]
I'm seeing this as well, 0.2.3. Here's a repo based off the component starter (the `shadow-prod` branch): https://github.com/mattdsteele/stencil-nested-shadows/tree/shadow-prod

In this instance, I've got this structure:

```
<my-component> // shadow: true
 <inner-shadow /> // shadow: true
 <inner-noshadow /> // shadow: false
</my-component>
```

With a production build I see different errors in different browsers:

* In Chrome, no hosts get a shadowRoot, and style tags are placed in the `<head>`.
* In Firefox/Edge, I see TypeErrors like "TypeError: this.Jn is undefined"

Might be related to another ticket, https://github.com/ionic-team/stencil/issues/447

**Comment by adamdbradley** [comment]
Thanks for the report, we'll dig into this, thanks

**Comment by peterpeterparker** [comment]
If that could help, I have the feeling that just using the `lazy-img` of the `ionic-pwa-toolkit` allow to replicate this issue. After a prod build, `this.el.shadowRoot` in this component gonna be `null`

**Comment by dimi-nk** [comment]
Problem still visible in `0.3.0`

**Comment by adamdbradley** [comment]
Thanks everyone for finding and fixing this! Turns out it was a pretty simple fix (just hard to find of course). Just needed to make sure "encapsulation" wasn't property renamed in the production builds. Should be fixed in the next release, thanks!

**Comment by nataje4** [comment]
I am still having this exact issue in 1.8.3. Should I create a new issue? Seems redundant—the problem is exactly as described here.

**Comment by AdrielD** [comment]
Also having the same problem, with a brand new, default, Stencil application.

```
"dependencies": {
    "@stencil/core": "^2.0.1"
  },
```

**Comment by WilHolt** [comment]
i`m facing this same issue in 1.17.2

**Comment by splitinfinities** [comment]
Hey folks! Could you please update Stencil to v2.10.0 and tell me if this still occurs? We are not supporting Stencil v0 or v1.
